version: '3.3'

networks:
  monitoring:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus:/etc/prometheus/
      - ./prometheus/prometheus_data:/prometheus
    command:
      - '--config.file=./prometheus/prometheus.yml'
    ports:
      - 9100:9100
    networks:
      - monitoring
    restart: always


  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - monitoring
    restart: always
